# 配置数据源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/study?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  # 配置xml映射文件路径
  mapper-locations: classpath:mapper/*.xml