package com.demo.model;

public class PersonCard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_card.card_id
     *
     * @mbg.generated Thu Mar 28 03:02:15 CST 2019
     */
    private Integer cardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_card.person_id
     *
     * @mbg.generated Thu Mar 28 03:02:15 CST 2019
     */
    private Integer personId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_card.card_id
     *
     * @return the value of person_card.card_id
     *
     * @mbg.generated Thu Mar 28 03:02:15 CST 2019
     */
    public Integer getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_card.card_id
     *
     * @param cardId the value for person_card.card_id
     *
     * @mbg.generated Thu Mar 28 03:02:15 CST 2019
     */
    public void setCardId(Integer cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_card.person_id
     *
     * @return the value of person_card.person_id
     *
     * @mbg.generated Thu Mar 28 03:02:15 CST 2019
     */
    public Integer getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_card.person_id
     *
     * @param personId the value for person_card.person_id
     *
     * @mbg.generated Thu Mar 28 03:02:15 CST 2019
     */
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }
}