package com.demo.dao;

import com.demo.model.PersonCard;
import com.demo.model.PersonCardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_card
     *
     * @mbg.generated Thu Mar 28 03:02:15 CST 2019
     */
    long countByExample(PersonCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_card
     *
     * @mbg.generated Thu Mar 28 03:02:15 CST 2019
     */
    int deleteByExample(PersonCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_card
     *
     * @mbg.generated Thu Mar 28 03:02:15 CST 2019
     */
    int deleteByPrimaryKey(Integer cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_card
     *
     * @mbg.generated Thu Mar 28 03:02:15 CST 2019
     */
    int insert(PersonCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_card
     *
     * @mbg.generated Thu Mar 28 03:02:15 CST 2019
     */
    int insertSelective(PersonCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_card
     *
     * @mbg.generated Thu Mar 28 03:02:15 CST 2019
     */
    List<PersonCard> selectByExample(PersonCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_card
     *
     * @mbg.generated Thu Mar 28 03:02:15 CST 2019
     */
    PersonCard selectByPrimaryKey(Integer cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_card
     *
     * @mbg.generated Thu Mar 28 03:02:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") PersonCard record, @Param("example") PersonCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_card
     *
     * @mbg.generated Thu Mar 28 03:02:15 CST 2019
     */
    int updateByExample(@Param("record") PersonCard record, @Param("example") PersonCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_card
     *
     * @mbg.generated Thu Mar 28 03:02:15 CST 2019
     */
    int updateByPrimaryKeySelective(PersonCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_card
     *
     * @mbg.generated Thu Mar 28 03:02:15 CST 2019
     */
    int updateByPrimaryKey(PersonCard record);
}